### ISSUE TITLE
qaq

### ISSUE THREAD

**Issue by arkerny** [fjy666/OICompare#1]
就是说没有开源还放GayHUB

**Comment by fjy666** [comment]
> 就是说没有开源还放GayHUB

额，目前代码太谔谔了，等过一会增加更多功能的时候会放上去的

**Comment by fjy666** [comment]
@arkerny

**Comment by arkerny** [comment]
就是说你发上来看看我还可以发pull request

**Comment by arkerny** [comment]
（大概可以新开一个仓库（雾

**Comment by arkerny** [comment]
又：忘记介绍了，CHZX新高一FPY

**Comment by fjy666** [comment]
@arkerny Uploaded. （学校名隐藏）新初一FJY qwq

**Comment by arkerny** [comment]
emmmmm
大概知道
CHZX见过

**Comment by arkerny** [comment]
就是说大概可以关掉了
